### ISSUE TITLE
Public Instance Monitor Increase Request

### ISSUE THREAD

**Issue by Social-Interactive** [zuedev/GameServerStatusDiscordBot#6]
`</Encryit>#9999`
https://discord.gg/CcReTbbFGc
5 more

**Comment by zuedev** [comment]
Hello @Social-Interactive, thank you for choosing to use the bot! I dropped by your Discord and couldn't see where you had the monitors running. What are you planning on using the extra slots for? 🙂

**Comment by Social-Interactive** [comment]
Hey, I use this for some game servers that im currently showing in the Discord, you couldnt see it because they must be activated in 819870324513701899 to see the games.

**Comment by zuedev** [comment]
> Hey, I use this for some game servers that im currently showing in the Discord, you couldnt see it because they must be activated in 819870324513701899 to see the games.

Got it, well I'll give you the benefit of the doubt with this one. I've increased your guild's limit by 5. If there's any further issues, please feel free to comment on this issue again.
